# This workflow will do a clean install of Java & Maven, start a Sauce Connect tunnel, then run a Java Test suite with that tunnel
name: Swag Labs Sample Java Test with Sauce Connect

on:
  push:
    branches:
      - main
      - diego-changes
  pull_request:
  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SAUCE_TUNNEL_NAME: ${{ secrets.SAUCE_TUNNEL_NAME }}
  BUILD_PREFIX: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sauce Connect Action
        uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: ${{ secrets.SAUCE_TUNNEL_NAME }}
          scVersion: 4.6.4

      #- name: Build Your App
          # Add code here to build your app

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        continue-on-error: true
        run: cd java_tests && mvn test
